//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Drawing;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace WFC4All.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("WFC4All.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Advance {
            get {
                object obj = ResourceManager.GetObject("Advance", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap AdvanceClick {
            get {
                object obj = ResourceManager.GetObject("AdvanceClick", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap AdvanceDisabled {
            get {
                object obj = ResourceManager.GetObject("AdvanceDisabled", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap AdvanceHover {
            get {
                object obj = ResourceManager.GetObject("AdvanceHover", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Animate {
            get {
                object obj = ResourceManager.GetObject("Animate", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap AnimateClick {
            get {
                object obj = ResourceManager.GetObject("AnimateClick", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap AnimateDisabled {
            get {
                object obj = ResourceManager.GetObject("AnimateDisabled", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap AnimateHover {
            get {
                object obj = ResourceManager.GetObject("AnimateHover", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap borderPaddingDisabled {
            get {
                object obj = ResourceManager.GetObject("borderPaddingDisabled", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap borderPaddingEnabled {
            get {
                object obj = ResourceManager.GetObject("borderPaddingEnabled", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Entropy {
            get {
                object obj = ResourceManager.GetObject("Entropy", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap fastSpeed {
            get {
                object obj = ResourceManager.GetObject("fastSpeed", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Hilbert {
            get {
                object obj = ResourceManager.GetObject("Hilbert", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap iconPNG {
            get {
                object obj = ResourceManager.GetObject("iconPNG", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap LeastUsed {
            get {
                object obj = ResourceManager.GetObject("LeastUsed", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Lexical {
            get {
                object obj = ResourceManager.GetObject("Lexical", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Load {
            get {
                object obj = ResourceManager.GetObject("Load", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap LoadClick {
            get {
                object obj = ResourceManager.GetObject("LoadClick", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap LoadDisabled {
            get {
                object obj = ResourceManager.GetObject("LoadDisabled", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap LoadHover {
            get {
                object obj = ResourceManager.GetObject("LoadHover", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Loading {
            get {
                object obj = ResourceManager.GetObject("Loading", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Pause {
            get {
                object obj = ResourceManager.GetObject("Pause", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap PauseClick {
            get {
                object obj = ResourceManager.GetObject("PauseClick", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap PauseHover {
            get {
                object obj = ResourceManager.GetObject("PauseHover", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Random {
            get {
                object obj = ResourceManager.GetObject("Random", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Restart {
            get {
                object obj = ResourceManager.GetObject("Restart", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap RestartClick {
            get {
                object obj = ResourceManager.GetObject("RestartClick", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap RestartHover {
            get {
                object obj = ResourceManager.GetObject("RestartHover", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Revert {
            get {
                object obj = ResourceManager.GetObject("Revert", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap RevertClick {
            get {
                object obj = ResourceManager.GetObject("RevertClick", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap RevertDisabled {
            get {
                object obj = ResourceManager.GetObject("RevertDisabled", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap RevertHover {
            get {
                object obj = ResourceManager.GetObject("RevertHover", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap rotationRef {
            get {
                object obj = ResourceManager.GetObject("rotationRef", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap rotationRef1 {
            get {
                object obj = ResourceManager.GetObject("rotationRef1", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap rotationRef2 {
            get {
                object obj = ResourceManager.GetObject("rotationRef2", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap rotationRef3 {
            get {
                object obj = ResourceManager.GetObject("rotationRef3", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;samples&gt;
        ///    &lt;overlapping category=&quot;Fonts&quot; name=&quot;BrownFox&quot; patternSize=&quot;4&quot;/&gt;
        ///    &lt;overlapping category=&quot;Fonts&quot; name=&quot;Font&quot; patternSize=&quot;5&quot; periodic=&quot;True&quot;/&gt;
        ///
        ///    &lt;overlapping category=&quot;Knots&quot; name=&quot;Knot&quot; patternSize=&quot;3&quot; periodic=&quot;True&quot;/&gt;
        ///    &lt;overlapping category=&quot;Knots&quot; name=&quot;Link&quot; patternSize=&quot;3&quot; periodic=&quot;True&quot;/&gt;
        ///    &lt;overlapping category=&quot;Knots&quot; name=&quot;Link2&quot; patternSize=&quot;3&quot; periodic=&quot;True&quot;/&gt;
        ///    &lt;overlapping category=&quot;Knots&quot; name=&quot;Nested&quot; patternSize=&quot;3&quot; periodic=&quot;True&quot;/&gt;
        ///    &lt;overlapping categ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string samples {
            get {
                return ResourceManager.GetString("samples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Save {
            get {
                object obj = ResourceManager.GetObject("Save", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap SaveClick {
            get {
                object obj = ResourceManager.GetObject("SaveClick", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap SaveDisabled {
            get {
                object obj = ResourceManager.GetObject("SaveDisabled", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap SaveHover {
            get {
                object obj = ResourceManager.GetObject("SaveHover", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Simple {
            get {
                object obj = ResourceManager.GetObject("Simple", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap slowSpeed {
            get {
                object obj = ResourceManager.GetObject("slowSpeed", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Spiral {
            get {
                object obj = ResourceManager.GetObject("Spiral", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap Weighted {
            get {
                object obj = ResourceManager.GetObject("Weighted", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
    }
}
